### DISCUSSION TITLE
Ignore control plane nodes

### DISCUSSION THREAD

**Discussion by aivanov-citc** [kubernetes-sigs/node-feature-discovery#1892] [Q&A]
We have a cluster with 6 nodes, three of them are control plane nodes. We set NFD only on worker nodes.

When applying this rule,
```yaml
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: paravirtualization-type
spec:
  rules:
    - name: "x86-paravirtualization-type-VMX"
      labels:
        "feature.node.kubernetes.io/x86-paravirtualization-type": "VMX"
      matchFeatures:
        - feature: cpu.cpuid
          matchExpressions:
            VMX: {op: Exists}
    - name: "x86-paravirtualization-type-SVM"
      labels:
        "feature.node.kubernetes.io/x86-paravirtualization-type": "SVM"
      matchFeatures:
        - feature: cpu.cpuid
          matchExpressions:
            SVM: {op: Exists}

```
we constantly see errors in the logs that the control planes do not have the necessary attributes.

Is there a way to filter nodes, for example, by labels or something else, so as not to read the attributes of unnecessary nodes?
