### DISCUSSION TITLE
How to troubleshoot feature.d changes?

### DISCUSSION THREAD

**Discussion by cmontemuino** [kubernetes-sigs/node-feature-discovery#2160] [Q&A]
I don't get why NFD keeps adding labels to some of my GPU nodes, when it shouldn't. What I need is some pointers to identify the root cause.

If I get the labels from a node and `...| grep nvidia`:

```yaml
nvidia.com/cuda.driver-version.full: 570.124.06
nvidia.com/cuda.driver-version.major: "570"
nvidia.com/cuda.driver-version.minor: "124"
nvidia.com/cuda.driver-version.revision: "06"
nvidia.com/cuda.driver.major: "545"
nvidia.com/cuda.driver.minor: "23"
nvidia.com/cuda.driver.rev: "06"
nvidia.com/cuda.runtime-version.full: "12.8"
nvidia.com/cuda.runtime-version.major: "12"
nvidia.com/cuda.runtime-version.minor: "8"
nvidia.com/cuda.runtime.major: "12"
nvidia.com/cuda.runtime.minor: "3"
nvidia.com/gfd.timestamp: "1710967106"
nvidia.com/gpu.compute.major: "8"
nvidia.com/gpu.compute.minor: "0"
nvidia.com/gpu.count: "4"
nvidia.com/gpu.deploy.container-toolkit: "true"
nvidia.com/gpu.deploy.dcgm: "true"
nvidia.com/gpu.deploy.dcgm-exporter: "true"
nvidia.com/gpu.deploy.device-plugin: "true"
nvidia.com/gpu.deploy.driver: "true"
nvidia.com/gpu.deploy.gpu-feature-discovery: "true"
nvidia.com/gpu.deploy.mig-manager: "true"
nvidia.com/gpu.deploy.node-status-exporter: "true"
nvidia.com/gpu.deploy.operator-validator: "true"
nvidia.com/gpu.engines.copy: "7"
nvidia.com/gpu.engines.decoder: "5"
nvidia.com/gpu.engines.encoder: "0"
nvidia.com/gpu.engines.jpeg: "1"
nvidia.com/gpu.engines.ofa: "1"
nvidia.com/gpu.family: ampere
nvidia.com/gpu.machine: ThinkSystem-SR670-V2
nvidia.com/gpu.memory: "80640"
nvidia.com/gpu.mode: compute
nvidia.com/gpu.multiprocessors: "98"
nvidia.com/gpu.present: "true"
nvidia.com/gpu.product: NVIDIA-A100-80GB-PCIe-MIG-7g.80gb
nvidia.com/gpu.replicas: "1"
nvidia.com/gpu.sharing-strategy: none
nvidia.com/gpu.slices.ci: "7"
nvidia.com/gpu.slices.gi: "7"
nvidia.com/mig.capable: "true"
nvidia.com/mig.config: all-disabled
nvidia.com/mig.config.state: success
nvidia.com/mig.strategy: single
nvidia.com/mps.capable: "false"
nvidia.com/vgpu.present: "false"
```

These are the labels that does not make sense from above:
```yaml
nvidia.com/cuda.driver.major: "545"
nvidia.com/cuda.driver.minor: "23"
nvidia.com/cuda.driver.rev: "06"
nvidia.com/gpu.product: NVIDIA-A100-80GB-PCIe-MIG-7g.80gb
nvidia.com/gpu.slices.ci: "7"
nvidia.com/gpu.slices.gi: "7"
```

So, I've removed the labels and added this one: `nvidia.com/gpu.product: NVIDIA-A100-80GB-PCIe`

_Note: I've also tried to remove annotation `nfd.node.kubernetes.io/feature-labels` first._

👉 After a few seconds, everything gets reverted back, and this is what I don't understand 🤔.

This is a GPU node and I have the gpu-operator running behind the scenes. This operator has a deamonset writing a set of labels in a directory for NFD to add labels afterwards. Logs:

```shell
I0519 09:40:50.420211      51 output.go:82] Writing labels to output file /etc/kubernetes/node-feature-discovery/features.d/gfd
I0519 09:40:50.420737      51 main.go:287] Sleeping for 30000000000
```

Looking at that file:
```shell
cat /etc/kubernetes/node-feature-discovery/features.d/gfd
nvidia.com/cuda.runtime.minor=8
nvidia.com/gpu.replicas=1
nvidia.com/gpu.family=ampere
nvidia.com/gpu.count=4
nvidia.com/gpu.memory=81920
nvidia.com/gfd.timestamp=1746706627
nvidia.com/vgpu.present=false
nvidia.com/cuda.runtime.major=12
nvidia.com/cuda.runtime-version.minor=8
nvidia.com/mps.capable=false
nvidia.com/cuda.driver-version.full=570.124.06
nvidia.com/gpu.compute.minor=0
nvidia.com/cuda.driver-version.minor=124
nvidia.com/mig.strategy=single
nvidia.com/gpu.machine=ThinkSystem-SR670-V2
nvidia.com/mig.capable=true
nvidia.com/gpu.product=NVIDIA-A100-80GB-PCIe
nvidia.com/cuda.driver.rev=06
nvidia.com/cuda.runtime-version.major=12
nvidia.com/cuda.driver.major=570
nvidia.com/cuda.runtime-version.full=12.8
nvidia.com/cuda.driver-version.revision=06
nvidia.com/gpu.sharing-strategy=none
nvidia.com/gpu.compute.major=8
nvidia.com/cuda.driver.minor=124
nvidia.com/cuda.driver-version.major=570
nvidia.com/gpu.mode=compute
```

Logs from `nfd-worker` running in the node looks pretty normal:
```
I0519 09:41:42.634897       1 nfd-worker.go:564] "starting feature discovery..."
I0519 09:41:42.635283       1 nfd-worker.go:577] "feature discovery completed"
I0519 09:42:42.635994       1 nfd-worker.go:564] "starting feature discovery..."
I0519 09:42:42.636399       1 nfd-worker.go:577] "feature discovery completed"
```

Logs from `nfd-master`:
```
I0502 10:52:28.072390       1 nfd-master.go:1230] "configuration file parsed" path="/etc/kubernetes/node-feature-discovery/nfd-master.conf"
I0502 10:52:28.072705       1 nfd-master.go:1275] "configuration successfully updated" configuration=<
        AutoDefaultNs: true
        DenyLabelNs: {}
        EnableTaints: true
        ExtraLabelNs:
          nvidia.com: {}
        Klog: {}
        LabelWhiteList: null
        LeaderElection:
          LeaseDuration:
            Duration: 15000000000
          RenewDeadline:
            Duration: 10000000000
          RetryPeriod:
            Duration: 2000000000
        NfdApiParallelism: 10
        NoPublish: false
        Restrictions:
          AllowOverwrite: true
          DenyNodeFeatureLabels: false
          DisableAnnotations: false
          DisableExtendedResources: false
          DisableLabels: false
          NodeFeatureNamespaceSelector: null
        ResyncPeriod:
          Duration: 3600000000000
```

ConfigMaps:

```yaml
# kubectl -n node-feature-discovery get cm nfd-node-feature-discovery-master-conf -oyaml
apiVersion: v1
data:
  nfd-master.conf: "null"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: nfd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/version: v0.17.3
    helm.sh/chart: node-feature-discovery-0.17.3
  name: nfd-node-feature-discovery-master-conf
  namespace: node-feature-discovery

---

# kubectl -n node-feature-discovery get cm nfd-node-feature-discovery-worker-conf -oyaml
apiVersion: v1
data:
  nfd-worker.conf: |-
    core:
      cacheTTL: 30s
      sleepInterval: 60s
    sources:
      cpu:
        cpuid:
          attributeBlacklist:
          - BMI1
          - BMI2
          - CLMUL
          - CMOV
          - CX16
          - ERMS
          - F16C
          - LZCNT
          - MMX
          - MMXEXT
          - NX
          - POPCNT
          - RDRAND
          - RDSEED
          - RDTSCP
          - SGX
          - SGXLC
          - SSE
          - SSE2
          - SSE3
          - SSE4.1
          - SSE4.2
          - SSSE3
          - TDX_GUEST
      local:
        dir: /etc/kubernetes/node-feature-discovery/features.d
        labels:
        - nvidia.com/*
      pci:
        deviceClassWhitelist:
        - "02"
        - "0200"
        - "0207"
        - "0300"
        - "0302"
        deviceLabelFields:
        - vendor
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: nfd
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: node-feature-discovery
    app.kubernetes.io/version: v0.17.3
    helm.sh/chart: node-feature-discovery-0.17.3
  name: nfd-node-feature-discovery-worker-conf
  namespace: node-feature-discovery
```

I'm using version `v0.17.3`.

🥺  Any help is highly appreciated!!
