### ISSUE TITLE
Status for NodeFeatureRule CRD

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1072]
**What would you like to be added**:

Add status field to the NodeFeatureRule CRD, indicating e.g. when the NodeFeatureRule was last processed, which nodes (and when) were affected, any errors etc.

**Why is this needed**:

Better visibility to the current state of matters

**Comment by marquiz** [comment]
Revived by the discussion in #1487, we could add at least the list of nodes (that matched) in the status. And that should probably be per Rule

```yaml
status:
  rules:
  - name: "rule-1"
    matchedNodes:
    - node-1
    - node-3
  - name: "rule-2"
    matchedNodes:
    - node-22
```
