### ISSUE TITLE
NFD not honoring USB serial number

### ISSUE THREAD

**Issue by rwlove** [kubernetes-sigs/node-feature-discovery#1094]
**What happened**:

Configured a custom NFD rule to match on USB class, vendor, device and serial, but NFD seemly ignores the serial number. Both workers get two labels for each device, when worker5 should get ztick-7 only and worker8 should get skyconnect only.

```
worker5.thesteamedcrab.com   Ready    <none>          22h   v1.25.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,feature.node.kubernetes.io/custom-skyconnect=t
rue,feature.node.kubernetes.io/custom-zstick-7=true,feature.node.kubernetes.io/pci-0300_1b36.present=true,feature.node.kubernetes.io/usb-03_0627_0001.present=true,feature.nod
e.kubernetes.io/usb-ff_10c4_ea60.present=true,kubernetes.io/arch=amd64,kubernetes.io/hostname=worker5.thesteamedcrab.com,kubernetes.io/os=linux,node.longhorn.io/create-defaul
t-disk=true
worker8.thesteamedcrab.com   Ready    <none>          22h   v1.25.5   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,feature.node.kubernetes.io/custom-skyconnect=t
rue,feature.node.kubernetes.io/custom-zstick-7=true,feature.node.kubernetes.io/pci-0300_1b36.present=true,feature.node.kubernetes.io/usb-03_0627_0001.present=true,feature.nod
e.kubernetes.io/usb-ff_10c4_ea60.present=true,kubernetes.io/arch=amd64,kubernetes.io/hostname=worker8.thesteamedcrab.com,kubernetes.io/os=linux,node.longhorn.io/create-defaul
t-disk=true
```

I also configured NFD to label based on serial number and it doesn't do that either.

I have two different USB sticks (zstick-7 and skyconnect) that share the same class, vendor and device so I need to use the serial number to differentiate the two different devices.

```
[root@worker8 ~]# udevadm info -a -n /dev/skyconnect | grep '{serial}'
    ATTRS{serial}=="1aa1ebd20a41ed11be6c7aa7ccf2b06c"
    ATTRS{serial}=="0000:00:1d.1" (this is the parent device)
```

```
[root@worker5 ~]# udevadm info -a -n /dev/zstick-7 | grep '{serial}'  
    ATTRS{serial}=="e88dc6f033e4ea1195decc9b994a5d01"
    ATTRS{serial}=="0000:02:00.0" (this is the parent device)
```

```
      sources:
        usb:                                                                                                                                                                  
          deviceClassWhitelist:                                                                                                                                               
            - "02"
            - "03"
            - "0e"
            - "ef"
            - "fe"
            - "ff"
          deviceLabelFields:                                                                                                                                                  
            - "class"
            - "vendor"
            - "device"
            - "serial"
       custom:                                                                                                                                                               
          - name: "skyconnect"
            matchOn:                                                                                                                                                          
              - usbId:                                                                                                                                                        
                  class: ["ff"]
                  vendor: ["10c4"]
                  device: ["ea60"]
                  serial: ["1aa1ebd20a41ed11be6c7aa7ccf2b06c"]          
          - name: "zstick-7"
            matchOn:                                                                                                                                                          
              - usbId:                                                                                                                                                        
                  class: ["ff"]
                  vendor: ["10c4"]
                  device: ["ea60"]
                  serial: ["e88dc6f033e4ea1195decc9b994a5d01"]
```

**What you expected to happen**:

The skyconnect device should be identified on worker8 and the zstick-7 should be identified on worker5. Also, the non-custom label should include the serial number.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

udev rules correctly match with the serial number.

```
[root@worker8 ~]# cat /etc/udev/rules.d/98-zstick.rules 
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="e88dc6f033e4ea1195decc9b994a5d01", SYMLINK+="zstick-7"
[root@worker8 ~]# ls /dev/skyconnect /dev/zstick-7
ls: cannot access '/dev/zstick-7': No such file or directory
/dev/skyconnect
```

```
[root@worker5 ~]# cat /etc/udev/rules.d/95-skyconnect.rules
SUBSYSTEM=="tty", ATTRS{idVendor}=="10c4", ATTRS{idProduct}=="ea60", ATTRS{serial}=="1aa1ebd20a41ed11be6c7aa7ccf2b06c", SYMLINK+="skyconnect"
➜  ~ ls /dev/skyconnect /dev/zstick-7      
ls: cannot access '/dev/skyconnect': No such file or directory
/dev/zstick-7
```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.25.5
- Cloud provider or hardware configuration: bare metal / homelab
- OS (e.g: `cat /etc/os-release`): CentOS 8 Stream
- Kernel (e.g. `uname -a`): Linux worker8.thesteamedcrab.com 4.18.0-408.el8.x86_64
- Install tools: Flux2, Helm
- Network plugin and version (if this is a network-related bug): Cilium
- Others: N/A

**Comment by marquiz** [comment]
Hmm, look like NFD is not detecting the devices. The device discovery is based on `/sys/bus/usb` which means that the kernel driver for the device(s) must be loaded. Could that be the case?

In order to see details about what nfd-worker is doing in this case you could add this to your config and grab the logs:

```yaml
core:
  featureSources: ["usb"]
  labelSources: ["usb", "custom"]
  klog:
    v: 4
```

**Comment by rwlove** [comment]
The labels on the nodes are shown at the top of my original post (please let me know if you need something else).

```
    image:
      repository: quay.io/kubernetes_incubator/node-feature-discovery
      tag: v0.6.0
```

Your question triggered me to look at the Helm chart source and I'm running NFD from a deprecated Helm chart. I'll update the chart too and see if it helps. I'll report back once I have some data.

Thanks for your assistance.

**Comment by marquiz** [comment]
No problem, good that you solved it

**Comment by S3LL1G28** [comment]
Sorry to reopen, I've got the same problem and install nfd from helm. 
https://artifacthub.io/packages/helm/node-feature-discovery/node-feature-discovery

It seems that the serial is not seen.

my udevadm:
```
udevadm info /dev/zigbee
P: /devices/pci0000:00/0000:00:1e.0/0000:05:02.0/0000:07:1b.0/usb9/9-6/9-6:1.0/tty/ttyACM1
N: ttyACM1
L: 0
S: zigbee
S: serial/by-path/pci-0000:07:1b.0-usb-0:6:1.0
S: serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2287323-if00
E: DEVPATH=/devices/pci0000:00/0000:00:1e.0/0000:05:02.0/0000:07:1b.0/usb9/9-6/9-6:1.0/tty/ttyACM1
E: DEVNAME=/dev/ttyACM1
E: MAJOR=166
E: MINOR=1
E: SUBSYSTEM=tty
E: USEC_INITIALIZED=9339545725
E: ID_BUS=usb
E: ID_VENDOR_ID=1cf1
E: ID_MODEL_ID=0030
E: ID_PCI_CLASS_FROM_DATABASE=Serial bus controller
E: ID_PCI_SUBCLASS_FROM_DATABASE=USB controller
E: ID_PCI_INTERFACE_FROM_DATABASE=XHCI
E: ID_VENDOR_FROM_DATABASE=Dresden Elektronik
E: ID_MODEL_FROM_DATABASE=ZigBee gateway [ConBee II]
E: ID_VENDOR=dresden_elektronik_ingenieurtechnik_GmbH
E: ID_VENDOR_ENC=dresden\x20elektronik\x20ingenieurtechnik\x20GmbH
E: ID_MODEL=ConBee_II
E: ID_MODEL_ENC=ConBee\x20II
E: ID_REVISION=0100
E: ID_SERIAL=dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2287323
E: ID_SERIAL_SHORT=DE2287323
E: ID_TYPE=generic
E: ID_USB_INTERFACES=:020201:0a0000:
E: ID_USB_INTERFACE_NUM=00
E: ID_USB_DRIVER=cdc_acm
E: ID_USB_CLASS_FROM_DATABASE=Communications
E: ID_PATH=pci-0000:07:1b.0-usb-0:6:1.0
E: ID_PATH_TAG=pci-0000_07_1b_0-usb-0_6_1_0
E: ID_MM_CANDIDATE=1
E: DEVLINKS=/dev/zigbee /dev/serial/by-path/pci-0000:07:1b.0-usb-0:6:1.0 /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2287323-if00
E: TAGS=:systemd:
E: CURRENT_TAGS=:systemd:

```


my nodefeaturerule:

```
---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: zigbee-device
  namespace: node-feature-discovery
spec:
  rules:
    - # zigbee conbee2
      name: zigbee.device
      labels:
        zigbee.feature.node.kubernetes.io/zigbee: "true"
      matchFeatures:
        - feature: usb.device
          matchExpressions:
            vendor: { op: In, value: ["1cf1"] }
            device: { op: In, value: ["0030"] }
            serial: { op: In, value: ["dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2287323"] }
```

Do you need more informations ?
