### ISSUE TITLE
NodeFeatureRule: dynamic values for labels

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1192]
**What would you like to be added**:

For extended resources (`extendedResources` field in NodeFeatureRule) we have a handy `@` notation for dynamically setting the value (capacity) of an extended resource. It would be nice to support this for labels, too. That is, having something like (just a random example):

```yaml
spec:
  rules:
    - name: "my dynamic label value rule"
      labels:
        linux-lsm-enabled: "@kernel.config.LSM"
```

Which would then create label like `feature.node.kubernetes.io/lsm-enabled=apparmor`

This can be already achieved with templating but it's rather cumbersome for something simple like this.

**Why is this needed**:

More flexible labeling. Avoid using templates for simple cases of dynamic label values.
