### ISSUE TITLE
source/pci: PCI device counts

### ISSUE THREAD

**Issue by mythi** [kubernetes-sigs/node-feature-discovery#1313]
**What would you like to be added**:
A possibility to create a rule that specifies how many PCI devices of certain ID are available.

**Why is this needed**:
For example, Intel Xeon 4th Gen has an accelerator block that has varying amount of PCI accelerators depending on the version available. This feature would bring cluster admins visibility to the available "resources".

**Comment by marquiz** [comment]
You should be able to achieve this with [templating](https://kubernetes-sigs.github.io/node-feature-discovery/v0.13/usage/customization-guide.html#templating). For example, to count all devices in class 02* smth like this:

```yaml
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: counter-rule
spec:
  rules:
    - name: "count pci devices"
      labelsTemplate: |
        foo.bar.count={{ len .pci.device }}
      matchFeatures:
      - feature: pci.device
        matchExpressions:
          class: {op: InRegexp, value: ["^02"]}
```

You could then use a more specific rule to count only certain devices
