### ISSUE TITLE
Labels converted to resources are also kept also as labels

### ISSUE THREAD

**Issue by tkatila** [kubernetes-sigs/node-feature-discovery#1376]
**What happened**:
Previously, we told NFD to convert a node label into a resource by the app arguments. Now when we moved to using NodeFeatureRules for the label->resource conversion, we see that the label is still visible in node's labels. Previously the label vanished when it got converted into a resource.

**What you expected to happen**:
Labels that are converted into resources should be removed from labels.

**How to reproduce it (as minimally and precisely as possible)**:
Our GPU plugin exports a set of labels via features.d directory:
```
gpu.intel.com/cards=card0
gpu.intel.com/gpu-numbers=0
gpu.intel.com/memory.max=0
gpu.intel.com/millicores=1000
gpu.intel.com/tiles=1
```
And from these, we convert the following resources:
```
gpu.intel.com/memory.max:       0
gpu.intel.com/millicores:       1k
gpu.intel.com/tiles:            1
```
With this rule:
```
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-gpu-platform-labeling
spec:
  rules:
  - extendedResources:
      gpu.intel.com/millicores: "@local.label.gpu.intel.com/millicores"
      gpu.intel.com/memory.max: "@local.label.gpu.intel.com/memory.max"
      gpu.intel.com/tiles: "@local.label.gpu.intel.com/tiles"
    matchFeatures:
      - feature: local.label
        matchExpressions:
          gpu.intel.com/millicores: {op: Exists}
          gpu.intel.com/memory.max: {op: Exists}
          gpu.intel.com/tiles: {op: Exists}
    name: intel.gpu.fractionalresources
```
Labels for the node after the resources have been converted:
```
kubectl get node -o json | jq .items[0].metadata.labels
{
...
  "gpu.intel.com/cards": "card0",
  "gpu.intel.com/device-id.0300-9a49.count": "1",
  "gpu.intel.com/device-id.0300-9a49.present": "true",
  "gpu.intel.com/gpu-numbers": "0",
  "gpu.intel.com/memory.max": "0",
  "gpu.intel.com/millicores": "1000",
  "gpu.intel.com/tiles": "1",
...
}
```

**Environment**:
NFD 0.14.0

**Comment by marquiz** [comment]
Thanks @tkatila for raising this. I think this should be considered a new feature/enhancement instead of a bug. Anyway, one way to address this would be to extend the local source (`source/local/`) and its feature file syntax to support "raw features", i.e. features that can be used in NodeFeatureRules but that are not automatically exposed as node labels. One immediate question with this what would be the syntax for the raw features? 😅

/cc @ArangoGutierrez @AhmedGrati @mythi @eero-t
/kind feature

**Comment by tkatila** [comment]
I wanted to highlight that we'd still want to keep the non-resource labels as they are. An example from the GPU labels:
```
gpu.intel.com/cards=card0
gpu.intel.com/gpu-numbers=0
gpu.intel.com/memory.max=0
gpu.intel.com/millicores=1000
gpu.intel.com/tiles=1
```
To resources:
```
gpu.intel.com/memory.max=0
gpu.intel.com/millicores=1000
gpu.intel.com/tiles=1
```
Keep as labels:
```
gpu.intel.com/cards=card0
gpu.intel.com/gpu-numbers=0
```

**Comment by marquiz** [comment]
> I wanted to highlight that we'd still want to keep the non-resource labels as they are. An example from the GPU labels:

Yes, definitely. Some "syntax options" include:

1. The Golang-style tags/directives that we already have for expiry-time
  ```
  gpu.intel.com/cards=card0
  # +noLabel
  gpu.intel.com/millicores=1000
  ```
2. Some prefix (the colon character `:` just as an example here)
  ```
  gpu.intel.com/cards=card0
  :gpu.intel.com/millicores=1000
  ```
3. Golang "struct annotation" style (looks too complex to me)
  ```
  gpu.intel.com/cards=card0
  gpu.intel.com/millicores=1000 `label:"false"`
  ```

Plz comment and feel free to suggest something else...

**Comment by tkatila** [comment]
> Plz comment and feel free to suggest something else...

I'd vote for the first version: # +noLabel

**Comment by marquiz** [comment]
My initial thinking is that we'd add a new `local.features` feature (to be consumed by the NFR rules)  which would contain the no-label stuff from feature files (and hooks fwiw). With this, the question then is should this `local.features` also include all the labels (i.e. all `local.labels`)?

One corner case/caveat to handle is conflict/overlap with labels wrt no-label features. I.e. what to do in the following case:

```
foo=bar
# +noLabel
foo=baz
```

Have both the label and the raw feature or just the raw feature? 🤔

**Comment by marquiz** [comment]
> I'd vote for the first version: # +noLabel

Maybe we could go with this. I thinkg `noLabel` would probably be a good/descriptive/understandable name for the directive.

But with this, I'm taking back some of my words in the earlier [comment](https://github.com/kubernetes-sigs/node-feature-discovery/issues/1376#issuecomment-1729426554) (the EDIT part): Now that looking at it, it somehow feels to me that the `noLablel` name implies semantics where the key=value pairs from the feature file(s) would be put in a common/single store from which labels and raw features are then created. So with this we would have two "raw features" from the local source:

- `local.features`: everything, i.e. all key=value pairs from the feature files 
- `local.labels`: same as the node labels that are generated, i.e. all key=value pairs that are not tagged with `# +noLabel`

So back to my example in a previous comment. With:

```
my-feature=value
foo=bar
# +noLabel
foo=baz
```

We'd get:
```yaml
local.features:
  foo: baz
  my-feature: value
local.labels:
  my-feature: value
```

Also, it feels to me that the `noLablel` should be per-feature, only apply to the next <key>=<value> pair encountered, unlike the `expiry-time`.

WDYT @tkatila @AhmedGrati @ArangoGutierrez @eero-t?
