### ISSUE TITLE
Specify resource limits (and requests) in NFD deployment files

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#1616]
**What would you like to be added**:

Refs #1614 

We should specify resource requests (cpu and memory requests and limits) in the NFD deployment files. I.e. both kustomize and Helm chart.

**Why is this needed**:

Best practices.

**Comment by ArangoGutierrez** [comment]
We have https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/deployment/helm/node-feature-discovery/values.yaml#L96

Commented and with a low request/limit. moving forward should be the opposite, it should be uncommented  and users can comment out if they feel to. 


Numbers should be
```yaml
     limits:
       cpu: 300m
       memory: 1G
     requests:
       cpu: 100m
       memory: 128Mi
```
