### ISSUE TITLE
Add generic `kernel.modules` feature that is an alias for `kernel.loadedmodule` and `kernel.enabledmodule`

### ISSUE THREAD

**Issue by mfranczy** [kubernetes-sigs/node-feature-discovery#1970]
**What would you like to be added**:
I would like to add a new feature `kernel.module` that's an alias for discovered `kernel.enabledmodules` and `kernel.loadedmodule`.

**Why is this needed**:
Currently, to check if a kernel module exists using NFR, you need to write OR conditions for each kernel module. This accounts for the possibility that the module is either loadable or built-in.

Here’s an example of such conditions in NFR:
```yaml
...
  rules:
  - name: "kernel module A"
    matchAny:
    - matchFeatures:
      - feature: kernel.enabledmodule
        matchExpressions:
          moduleA: {op: Exists}
    - matchFeatures:
      - feature: kernel.loadedmodule
        matchExpressions:
          moduleA: {op: Exists}
  - name: "kernel module B"
    matchAny:
    - matchFeatures:
      - feature: kernel.enabledmodule
        matchExpressions:
          moduleB: {op: Exists}
    - matchFeatures:
      - feature: kernel.loadedmodule
        matchExpressions:
          moduleB: {op: Exists}
```

The expected output from the issue is the following rule:

```yaml
...
  rules:
  - name: "kernel modules"
    - matchFeatures:
      - feature: kernel.module
        matchExpressions:
          moduleA: {op: Exists}
          moduleB: {op: Exists}
```
