### ISSUE TITLE
PB discoverying SRIOV iGPU Intel 

### ISSUE THREAD

**Issue by S3LL1G28** [kubernetes-sigs/node-feature-discovery#1999]
**What happened**:

I want to discover iGPU from intel in a proxmox virtualized worker. I'm using passthrough of sriov intel igpu. I succeed to generate 3 virtualized iGPU  for my node.

**What you expected to happen**:
I want to discover my X iGPU on my nworker node
**How to reproduce it (as minimally and precisely as possible)**:
have INtel CPU gen 12th at minimum andd follow those instructions to activate the capability to virtualize your iGPU:
https://github.com/bbaa-bbaa/i915-sriov-dkms

**Anything else we need to know?**:
```
lspci | grep VGA
06:10.0 VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)
06:11.0 VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)
06:1b.0 VGA compatible controller: Intel Corporation AlderLake-S GT1 (rev 0c)
```
```
lspci -nn -s 06:10.0
06:10.0 VGA compatible controller [0300]: Intel Corporation AlderLake-S GT1 [8086:4680] (rev 0c)

lspci -nn -s 06:11.0
06:11.0 VGA compatible controller [0300]: Intel Corporation AlderLake-S GT1 [8086:4680] (rev 0c)

lspci -nn -s 06:1b.0
06:1b.0 VGA compatible controller [0300]: Intel Corporation AlderLake-S GT1 [8086:4680] (rev 0c)
```
VF iGPU is working as for example, I'm using it for jellyfin to make transcode.

Specific nfd setup in my nfd helm version 0.17:

in my values.yaml:

```
worker:
  enable: true
  config:
    core:
      sources: ["custom", "pci", "usb"]
    sources:
      pci:
        # https://pci-ids.ucw.cz/read/PD
        deviceClassWhitelist: ["0300", "01", "03", "0b40", "12"]
        deviceLabelFields:
          - "class"
          - "vendor"
          - "device"
          - "subsystem_vendor"
          - "subsystem_device"
      usb:
        deviceClassWhitelist: ["02", "03", "0e", "ef", "fe", "ff"]
        deviceLabelFields: ["class", "vendor", "device", "serial"]
      custom:
        - name: "intel-gpu" # Intel integrated GPU
          matchOn:
            - pciId:
                class: ["0300"]
                vendor: ["8086"]
```

my manifest for igpu
```
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-gpus
  namespace: node-feature-discovery
spec:
  rules:
    - name: intel-gpu-card0
      labels:
        feature.node.kubernetes.io/intel-gpu-card0.present: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: { op: In, value: ["8086"] }
            class: { op: In, value: ["0300"] }
            device: { op: In, value: ["4680"] }
            pciAddress: { op: In, value: ["0000:06:10.0"] }

    - name: intel-gpu-card1
      labels:
        feature.node.kubernetes.io/intel-gpu-card1.present: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: { op: In, value: ["8086"] }
            class: { op: In, value: ["0300"] }
            device: { op: In, value: ["4680"] }
            pciAddress: { op: In, value: ["0000:06:11.0"] }

    - name: intel-gpu-card2
      labels:
        feature.node.kubernetes.io/intel-gpu-card2.present: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor: { op: In, value: ["8086"] }
            class: { op: In, value: ["0300"] }
            device: { op: In, value: ["4680"] }
            pciAddress: { op: In, value: ["0000:06:1b.0"] }

```

**Environment**:
- Kubernetes version (use `kubectl version`): v1.30.0
- Cloud provider or hardware configuration: on premise with proxmox 8.3, intel 12700 CPU
- OS (e.g: `cat /etc/os-release`): Ubuntu 24.04.1 LTS
- Kernel (e.g. `uname -a`): `Linux k8sw4.gil-yan.net 6.8.0-51-generic #52-Ubuntu SMP PREEMPT_DYNAMIC Thu Dec  5 13:09:44 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: 
- Network plugin and version (if this is a network-related bug): cilium 1.15.4
- Others:

in case of, ansible task to install sriov igpu (not perfect but working):

ubuntu_kernel_version: "6.8.0-51"
ubuntu_kernel_release: "{{ubuntu_kernel_version}}-generic"

```
---
# tasks file for igpu-sriov

- name: Get kernel version
  command: uname -r
  register: kernel_version
  changed_when: false

- name: Add kernel and linux-headers
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - build-*
    - dkms
    - git
    - vim
    - "linux-headers-{{ ubuntu_kernel_release }}"
    - "linux-headers-{{ ubuntu_kernel_version }}"
    - "linux-image-{{ ubuntu_kernel_release }}"
    - "linux-modules-{{ ubuntu_kernel_release }}"
    - "linux-tools-{{ ubuntu_kernel_release }}"
    - "linux-modules-extra-{{ ubuntu_kernel_release }}"

- name: hold kubernetes binary versions (prevent from being updated)
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - "linux-headers-{{ ubuntu_kernel_release }}"
    - "linux-headers-{{ ubuntu_kernel_version }}"
    - "linux-image-{{ ubuntu_kernel_release }}"
    - "linux-modules-{{ ubuntu_kernel_release }}"
    - "linux-tools-{{ ubuntu_kernel_release }}"
    - "linux-modules-extra-{{ ubuntu_kernel_release }}"

- name: Add i915 module options to /etc/modprobe.d/i915.conf
  lineinfile:
    path: /etc/modprobe.d/i915.conf
    line: 'options i915 enable_guc=3'
    create: yes

- name: Add kernel parameters to GRUB_CMDLINE_LINUX_DEFAULT
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 intel_iommu=on iommu=pt i915.enable_guc=3"'
    backrefs: yes

- name: Update GRUB configuration
  command: update-grub
  when: ansible_os_family == "Debian"

- name: clone iGPU fork project for kernel 6.8
  ansible.builtin.git:
    repo: https://github.com/bbaa-bbaa/i915-sriov-dkms.git
    dest: i915-sriov-dkms/

- name: Check if i915-sriov-dkms module is already added
  shell: dkms status | grep -q "i915-sriov-dkms"
  register: dkms_status
  ignore_errors: yes
  changed_when: false

- name: Add i915-sriov-dkms module using DKMS
  command: dkms add .
  args:
    chdir: i915-sriov-dkms  # Optional: Change to the directory where the VERSION file is located
  when: dkms_status.rc != 0

- name: Check if i915-sriov-dkms module is already installed
  shell: dkms status | grep -q "i915-sriov-dkms, $(cat VERSION), $(uname -r), x86_64"
  args:
    chdir: i915-sriov-dkms  # Optional: Change to the directory where the VERSION file is located
  register: dkms_status
  ignore_errors: yes
  changed_when: false

- name: Install i915-sriov-dkms module using DKMS
  shell: >
    dkms install -m i915-sriov-dkms -v $(cat VERSION) -k $(uname -r) --force
  args:
    chdir: i915-sriov-dkms  # Optional: Change to the directory where the VERSION file is located
  environment:
    GUCFIRMWARE_MINOR: 17
  when: dkms_status.rc != 0

- name: Download firmware files using wget
  command: >
    wget -P ./firmware/i915 --random-wait -w 0.2 -r -nd -e robots=no -A '*.bin' --accept-regex '/plain/' https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/tree/i915/
  ignore_errors: yes
  changed_when: false
  # args:
  #   creates: ./firmware/i915

- name: Copy firmware files to /lib/firmware/i915/
  copy:
    src: ./firmware/i915/
    dest: /lib/firmware/i915/
    remote_src: yes

- name: Check if initramfs needs updating
  command: update-initramfs -u -k all
  register: initramfs_update
  changed_when: "'updating initramfs' in initramfs_update.stdout"
```

If you need more information tell me.

Thank you and Happy new year.
