### ISSUE TITLE
unprefixed keys are not allowed

### ISSUE THREAD

**Issue by ademariag** [kubernetes-sigs/node-feature-discovery#2074]
**What would you like to be added**: The ability to add no namespace

**Why is this needed**:
I am using GKE, and in order to use the Nvidia GPU Operator correctly I need to disable the installation of the device plugin by adding this label

gke-no-default-nvidia-gpu-device-plugin=true

see https://cloud.google.com/kubernetes-engine/docs/how-to/gpu-operator#setup-node-pool

I am using

```
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: gke-gpu-labeler
spec:
  rules:
    - name: label-gke-gpu-nodes
      labels:
        gke-no-default-nvidia-gpu-device-plugin: "true"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            vendor:
              op: In
              value:
                - 10de
```

which unfortunately produces `feature.node.kubernetes.io/gke-no-default-nvidia-gpu-device-plugin=true`

Unfortunately NFD offers no ways that I can see to remove the prefix namespace.
I understand that it is against best practices, but we're all adults :)
