### ISSUE TITLE
Allow templating of updateStrategy for worker DaemonSet

### ISSUE THREAD

**Issue by jon-rei** [kubernetes-sigs/node-feature-discovery#2127]
**What would you like to be added**:

Currently, the default updateStrategy for the DaemonSet is used, which is the following by default

```yaml
    updateStrategy:
      rollingUpdate:
        maxSurge: 0
        maxUnavailable: 1
```

The whole updateStrategy should be templatable with Helm to adjust the maxUnavailable setting or even other settings.

**Why is this needed**:

In our environment, we have hundreds of nodes, so a rollout takes a long time. Also, if a node is unhealthy, the rollout will stop. To overcome this, we always set maxUnavailable to 10% to speed up the rollout.
