### ISSUE TITLE
Nfd-Worker fails to communicate to Nfd-Master

### ISSUE THREAD

**Issue by PrahladaHerle** [kubernetes-sigs/node-feature-discovery#293]
Hi,

I am trying to use the NFD feature on my local cluster setup (logs - [localclusterlogs.zip](https://github.com/kubernetes-sigs/node-feature-discovery/files/4273867/localclusterlogs.zip))
It seems nfd-workers are not able to communicate with the nfd-master for reporting the node details.

I tried same experiment with katakoda playground (https://www.katacoda.com/courses/kubernetes/playground). It seems to be working fine there.
(logs - [katakodalogs.zip](https://github.com/kubernetes-sigs/node-feature-discovery/files/4273909/katakodalogs.zip))

I am a newbie to Kubernetes. Reply back if any information is missing or further details are needed.

Regards,
Prahlada Herle

**Comment by marquiz** [comment]
Hmm, must be something with your cluster setup.

What method are you using for deployment, the provided .yaml templates or something else? 

Is the service discovery DNS lookup working? You could do soemthing like 
```
$ kubectl -n node-feature-discovery exec -it pod/nfd-worker-64jn6 /bin/bash
```
And then inside the container
```
# echo > /dev/tcp/nfd-master/8080
```
If that returns and error (something like "nfd-master: Name or service not known") there is something wrong with the dns.

Do you happen to have some NetworkPolicy enabled in your cluster?

**Comment by marquiz** [comment]
Actually, taking a closer look at your logs the nfd-master service seems to run in different (wrong) ip subnet (10.109.0.0/16) than the other services (10.96.0.0/16). That's prolly the problem. Try re-creating the service

**Comment by PrahladaHerle** [comment]
Regarding the different subnet for the services, it is the same behavior in the katakoda experiment also (kubernetes/kube-dns services were in 10.96.0.X network and nfd-master service was in 10.100.32.X network).

I repeated the experiment in my setup. Yes, it seems to be a DNS and/or networking issues (could be host networking or cni plugin that I am using or other configuration parameters). I will check this further.

```
root@k8sworker1:/# echo > /dev/tcp/nfd-master/8080
bash: nfd-master: Temporary failure in name resolution
bash: /dev/tcp/nfd-master/8080: Invalid argument
```

Created a test pod with the following spec, and there is no issue in the test pod to reach nfd-master
```
[root@k8smaster nodefeaturediscovery]# cat test.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
  labels:
    app: test-app
  namespace: node-feature-discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: centos-container
          image: centos
          command: [ "sh", "-c", "sleep 1h" ]

```
