### ISSUE TITLE
How can I prevent from labeling/annotating 

### ISSUE THREAD

**Issue by gerardo8a** [kubernetes-sigs/node-feature-discovery#306]
I only need to annotate and label custom data. Using empty whitelist should do the trick? if have a simple configmap for example:

```
sources:
      cpu:
        cpuid:
          attributeWhitelist:
```

So I assume all cpu should be skipped? the node still has the annotations made before I added the new config.
