### ISSUE TITLE
Add support for arm64, armV7, armV8

### ISSUE THREAD

**Issue by utegental** [kubernetes-sigs/node-feature-discovery#426]
**What would you like to be added**:
There is no _arm_ support. It would be good to see support this for those architectures.

**Why is this needed**:
Getting "standard_init_linux.go:219: exec user process caused: exec format error" for pods scheduled on _arm_ nodes.
Usually it's easy to do - just making image multi-architecture =)

**Comment by marquiz** [comment]
I agree. There have been attempts in the past e.g. #203 and #327 at least. Now that we have K8s test-infra (gcb as the image builder) as the CI pipeline this might be doable

**Comment by Diaoul** [comment]
I would be interested in this as well. Can you elaborate on what kind of work is required to make this happen? From the previous PRs, it doesn't seem that a great deal of code is required.

**Comment by xUnholy** [comment]
One is currently being maintained in parity with upstream `docker.io/raspbernetes/node-feature-discovery` which is built for armv7 & arm64

**Comment by Diaoul** [comment]
Great! Maybe this can be merged upstream?

**Comment by zvonkok** [comment]
@marquiz We can easily do this with github actions
```
jobs:
  build_job:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.arch }}

    strategy:
      matrix:
        include:
          - arch: armv7
            distro: ubuntu20.04
          - arch: aarch64
            distro: ubuntu20.04
          - arch: s390x
            distro: ubuntu20.04
          - arch: ppc64le
            distro: ubuntu20.04
    steps:
```
