### ISSUE TITLE
NFD does not reveal all the features in cpuid for AMD Ryzen

### ISSUE THREAD

**Issue by ionutnechita** [kubernetes-sigs/node-feature-discovery#849]
<no-template>

Hi NFD Team,

I try today to deploy NFD in Kind Cluster.
But I noticed that there are differences between what NFD and cpuid discover.
There are fewer characteristics discovered by NFD compared to cpuid.

NFD version: k8s.gcr.io/nfd/node-feature-discovery:v0.11.1
CPUID go implementation version: cpuid-Linux_x86_64_2.0.14
OS: openSUSE Tumbleweed 20220706
Kind version: kind version 0.14.0
AMD CPU: AMD Ryzen 9 5900HS with Radeon Graphics

cpuid: [cpuid-go.txt](https://github.com/kubernetes-sigs/node-feature-discovery/files/9076575/cpuid-go.txt)
nfd labels + workers: [kubectl-nodes.txt](https://github.com/kubernetes-sigs/node-feature-discovery/files/9076576/kubectl-nodes.txt)

nfd features: [features-nfd.txt](https://github.com/kubernetes-sigs/node-feature-discovery/files/9076589/features-nfd.txt)
cpuid features: [features-cpuid.txt](https://github.com/kubernetes-sigs/node-feature-discovery/files/9076591/features-cpuid.txt)

Diff:
BMI1                                                          <
BMI2                                                          <
CLMUL                                                         <
CMOV                                                          <
CX16                                                          <
ERMS                                                          <
F16C                                                          <
HTT                                                           <
LZCNT                                                         <
MMX                                                           <
MMXEXT                                                        <
MSR_PAGEFLUSH                                                 <
NX                                                            <
POPCNT                                                        <
RDRAND                                                        <
RDSEED                                                        <
RDTSCP                                                        <
SEV                                                           <
SEV_64BIT                                                     <
SEV_ALTERNATIVE                                               <
SEV_DEBUGSWAP                                                 <
SEV_ES                                                        <
SEV_RESTRICTED                                                <
SME                                                           <
SSE                                                           <
SSE2                                                          <
SSE3                                                          <
SSE4                                                          <
SSE42                                                         <
SSSE3                                                         <
VTE                                                           <
XGETBV1                                                       <
XSAVEC                                                        <
XSAVEOPT                                                      <
XSAVES                                                        <

BR,
Ionut Nechita
ionutnechita

**Comment by fmuyassarov** [comment]
Hi @ionutnechita 
By default those cpu features are disabled from publishing via [attributeBlacklist](https://github.com/kubernetes-sigs/node-feature-discovery/blob/5d88692b198907b43bfea4f975889441109f3ca3/deployment/components/worker-config/nfd-worker.conf.example#L26). If you want to enable them, I would suggest you either to edit your configMap (namespace: `node-feature-discovery`, name:  `nfd-worker-conflive` if you are using default manifests from NFD) to uncomment `attributeBlacklist` so that the list is empty or do the same changes in the default [worker configuration file](https://github.com/kubernetes-sigs/node-feature-discovery/blob/v0.11.2/deployment/components/worker-config/nfd-worker.conf.example#L26) used for that configMap.
Example of config file would look like
```
    #core:
    #  labelWhiteList:
    #  noPublish: false
    #  sleepInterval: 60s
    #  featureSources: [all]
    #  labelSources: [all]
    #  klog:
    #    addDirHeader: false
    #    alsologtostderr: false
    #    logBacktraceAt:
    #    logtostderr: true
    #    skipHeaders: false
    #    stderrthreshold: 2
    #    v: 0
    #    vmodule:
    ##   NOTE: the following options are not dynamically run-time configurable
    ##         and require a nfd-worker restart to take effect after being changed
    #    logDir:
    #    logFile:
    #    logFileMaxSize: 1800
    #    skipLogHeaders: false
    sources:
      cpu:
        cpuid:
          attributeBlacklist:
    #  kernel:
    #    kconfigFile: "/path/to/kconfig"
    #    configOpts:
    #      - "NO_HZ"
    #      - "X86"
    #      - "DMI"

```


Ref: https://kubernetes-sigs.github.io/node-feature-discovery/v0.11/advanced/worker-configuration-reference.html#sourcescpu
